### ISSUE TITLE
相关资讯

### ISSUE THREAD

**Issue by Tsunami-Song** [GShyx/Idle-trading-platform#22]
请问关于聊天室的功能，是否完成了呢？
我在测试过程中发现了关于res.result.total的报错
不胜感谢！

**Comment by GShyx** [comment]
这是课程作业，最后一次提交时界面有的所有功能都完成了，当时我们在调试和真机上都可以做到正常聊天
由于是小组形式的作业，聊天室部分并不是我负责所以很抱歉我帮不到你。。

**Comment by Tsunami-Song** [comment]
感谢大佬，我会好好学习一下您的代码~对于报错的地方我会去调试解决的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "GShyx"<notifications@github.com&gt;; 
发送时间: 2020年9月29日(星期二) 晚上11:59
收件人: "GShyx/Idle-trading-platform"<Idle-trading-platform@noreply.github.com&gt;; 
抄送: "孤木成林"<1579167146@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [GShyx/Idle-trading-platform] 相关资讯 (#22)





 
这是课程作业，最后一次提交时界面有的所有功能都完成了，当时我们在调试和真机上都可以做到正常聊天
 由于是小组形式的作业，聊天室部分并不是我负责所以很抱歉我帮不到你。。

**Comment by GShyx** [comment]
不至于不至于，由于是课程作业学习性质比较重，所以代码中也有相当多不尽如人意的地方
如果能帮到你真是再好不过了
